# Nombre de la aplicación
spring.application.name=api

# Configuración de Base de Datos (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/bdFindimo
spring.datasource.username=postgres
spring.datasource.password=Pitisa14;,vvv
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Puerto del servidor
server.port=8080
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl